name: feedbin-tailscale
networks:
    feedbin-tailscale:
        name: feedbin-tailscale
services:
    feedbin-backend:
        container_name: feedbin-backend
        image: ghcr.io/disrel/feedbin-tailscale:edge
        hostname: feedbin-backend
        privileged: true
        environment:
            - TS_TAILNAME=${TS_TAILNAME}
            - TS_HOSTNAME=${TS_HOSTNAME}
        networks:
            - feedbin-tailscale
        ports:
            - 80:80/tcp
            - 443:443/tcp
        volumes:
            - /sys/fs/cgroup:/sys/fs/cgroup
            - ./feedbin-backend:/data
        devices:
            - /dev/fuse
        depends_on:
            - feedbin-frontend
        cgroup: host
    feedbin-frontend:
        container_name: feedbin-frontend
        image: tailscale/tailscale:latest
        hostname: feedbin
        environment:
            - TS_AUTHKEY=${TS_AUTHKEY}
            - TS_EXTRA_ARGS=--advertise-tags=tag:container # Check Tailscale documentation to add tags for ACL Management.
        volumes:
            - /dev/net/tun:/dev/net/tun
            - ./feedbin-frontend:/var/lib
        cap_add:
            - NET_ADMIN
            - NET_RAW
        restart: unless-stopped
