#!/bin/sh
set -e

if test "$#" -ne 1 -o -z "$1"; then
  echo "Usage: $0 hostname"
  exit 1
fi

configure () {
  echo "# $1" && test -e "$1" || tee "$1" && "${2:-.}" "$1" && echo
}

secure_random () {
  head -c 512 /dev/urandom | sha256sum | head -c 64
}

mkdir -p /data/elasticsearch/data \
         /data/feedbin \
         /data/minio/data \
         /data/postgresql/data \
         /data/redis/data \
         /var/run/postgresql

chown 1000:1000 /data/elasticsearch/data

configure /data/elasticsearch/.env : <<EOF
discovery.type=single-node
xpack.security.enabled=false
EOF

configure /data/minio/.env <<EOF
MINIO_HOST=http://127.0.0.1:9000
MINIO_ACCESS_KEY=$(secure_random)
MINIO_SECRET_KEY=$(secure_random)
EOF

configure /data/postgresql/.env : <<EOF
POSTGRES_USER=root
POSTGRES_PASSWORD=$(secure_random)
EOF

configure /data/redis/.env : <<EOF
EOF

configure /data/feedbin/.env <<EOF
DATABASE_URL=postgres:///feedbin_production
ELASTICSEARCH_URL=http://127.0.0.1:9200
REDIS_URL=redis://127.0.0.1:6379

SECRET_KEY_BASE=$(secure_random)

AWS_S3_ENDPOINT=http://127.0.0.1:9000
AWS_ACCESS_KEY_ID=$MINIO_ACCESS_KEY
AWS_SECRET_ACCESS_KEY=$MINIO_SECRET_KEY
AWS_S3_PATH_STYLE=true

EXTRACT_USER=$(secure_random)
EXTRACT_SECRET=$(secure_random)

RACK_ENV=production
RAILS_ENV=production

FEEDBIN_HOST=$1
EXTRACT_HOST=localhost
ENTRY_IMAGE_HOST=localhost
FAVICON_HOST=localhost

FEEDBIN_URL=https://$1
DEFAULT_URL_OPTIONS_HOST=$1
PUSH_URL=https://$1

AWS_S3_BUCKET=feedbin

FORCE_SSL=false
EOF
